[Su-25T] better images
lord-vesel/dcs-doc pull request #38
Opened 2021-04-07 07:42 UTC by alex-mos

Fixes #31

2021-04-07 15:00 UTC, alex-mos commented
Заодно убрал дублирование аббревиатур в Ми-8. В случае конфликтов можно подключать два файла аббревиатур — локальный после глобального. Тогда основные аббревиатуры берутся из глобального файла, а конфликтующие — из локального:

```
{!abbr.md!}
{!docs/mi8/abbr.md!}
```

#32

2021-04-07 20:34 UTC, lord-vesel requested changes
Со всем согласен, только ru/docs/mi8/15.abbr.md пусть останется как был.

2021-04-08 10:03 UTC, alex-mos commented
Вернул 15.abbr.md

2021-04-08 17:30 UTC, lord-vesel approved these changes
Спасибо, мержу.

2021-04-08 17:30 UTC, merged