fixes and L-39 init
lord-vesel/dcs-doc pull request #40
Opened 2021-04-28 13:23 UTC by alex-mos

2021-04-28 17:02 UTC, lord-vesel requested changes
Ё POWER!

2021-04-28 18:30 UTC, alex-mos commented
Fixed

2021-04-28 18:32 UTC, alex-mos commented
Пардон, не заметил что гитхаб свернул часть замечаний. Ещё 20 минут.

2021-04-28 18:41 UTC, alex-mos commented
Теперь точно fixed.

2021-04-29 11:02 UTC, itsystem approved these changes
Огонь, спасибо.

2021-04-29 11:51 UTC, lord-vesel approved these changes
Теперь точно огонь спасибо.

2021-04-29 11:52 UTC, merged