markdown lint
lord-vesel/dcs-doc pull request #63
Opened 2022-01-31 08:22 UTC by alex-mos

2022-01-31 19:16 UTC, lord-vesel requested changes
Подтяни изменения из мастера плз.

2022-02-03 17:01 UTC, alex-mos commented
Готово.

2022-09-07 14:25 UTC, alex-mos commented
@lord-vesel ребейснул ветку на мастер.

2022-09-07 20:41 UTC, lord-vesel commented
> @lord-vesel ребейснул ветку на мастер.

спасибо, постараюсь найти способ автоматизированно прочекать, что ничего не ломает

2022-09-10 11:22 UTC, alex-mos commented
Думаю что это можно качественно прочекать только скриншотными тестами, ну или какими-нибудь снапшотами html, и оба варианта выглядят достаточно громоздко. Предлагаю move fast and break things, тем более что это просто линтер который один раз пробегает по файлам.

2022-09-12 19:47 UTC, lord-vesel commented
> move fast and break things

typical developer

Тут не только просто линтер, есть правки текстовые, приходится всё проверять.

2022-09-12 21:22 UTC, lord-vesel commented
@alex-mos в общем, линтер добавляет кучу лишних строк и я подзадолбался их выковыривать, сделать бы с этим что-то массово

2022-09-13 09:05 UTC, alex-mos commented
Какие строки ты имеешь в виду? Я пробежался по диффу — он скорее поудалял много лишних строк. Если где-то добавляет строки, которые ломают вёрстку, то я его подкручу чтобы этого не делал.

2022-09-14 07:43 UTC, lord-vesel commented
> Какие строки ты имеешь в виду?

А выше в ревью, запрошенные изменения с комментами.
Линтер добавляет строку перед строкой, начинающейся с "-", считая, что это начало списка.

2022-10-02 08:16 UTC, lord-vesel requested changes
нужно пофиксить списки, которые понаделал линтер из абзацев, стартующих с дефиса

2022-10-03 14:20 UTC, alex-mos commented on ru/docs/p-47/02.history.md
> -## Быть или не быть!
fixed

2022-10-03 14:20 UTC, alex-mos commented on ru/docs/spitfire-ix/02.common.md
> +
fixed

2022-10-03 14:21 UTC, alex-mos commented on ru/docs/spitfire-ix/01.intro.md
> +
fixed

2022-10-03 14:22 UTC, alex-mos commented on ru/docs/spitfire-ix/04.design.md
> +
fixed

2022-10-03 14:22 UTC, alex-mos commented on ru/docs/spitfire-ix/06.systems.md
> +
fixed

2022-10-03 14:23 UTC, alex-mos commented on ru/docs/spitfire-ix/07.flight.md
> +
fixed

2022-10-03 14:27 UTC, alex-mos commented on ru/docs/fa18c/02.cockpit.md
> +
Эта не лишняя:
<img width="712" alt="Screenshot 2022-10-03 at 16 26 47" src="https://user-images.githubusercontent.com/662046/193602355-4a59e35c-c5ec-4394-ac8b-e432ac9f0170.png">

2022-10-03 14:54 UTC, alex-mos commented on ru/docs/fa18c/10.a-a-mode.md
> +
fixed

2022-10-03 14:56 UTC, alex-mos commented on ru/docs/fa18c/09.a-g-mode.md
> +
fixed

2022-10-03 14:56 UTC, alex-mos commented on ru/docs/fa18c/08.nav-mode.md
> +
fixed

2022-10-03 15:55 UTC, alex-mos commented
Исправил места где линтер создавал лишние списки, отсмотрел глазами весь дифф в поисках подозрительных мест, проверил на сайте, внёс дополнительные правки по ходу ревью.

2025-05-21 10:59 UTC, closed without merging